name: Update Dependency Graph
on:
  workflow_call:
jobs:
  dependency-graph-sbt:
    name: Update Dependency Graph for SBT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: scalacenter/sbt-dependency-submission@v2
   