name: Simple Snyk monitor for SBT + Node

on:
  workflow_call:
    inputs:
      DEBUG:
        type: string
        required: false
      ORG:
        type: string
        required: true
      JAVA_VERSION:
        type: string
        required: false
        default: "11"
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - uses: snyk/actions/setup@0.3.0

            - uses: actions/setup-java@v2
              with:
                  java-version: ${{ inputs.JAVA_VERSION }}
                  distribution: "adopt"

            - name: Snyk monitor
              run: snyk monitor ${INPUT_DEBUG:+ -d} --all-projects --org="${{ inputs.ORG }}"
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                  INPUT_DEBUG: ${{ inputs.DEBUG }}
